import './globals.css'
import { Inter } from 'next/font/google'
import { StoreProvider } from '@/stores/StoreProvider'
import getToken from '@/lib/getToken'
import { store } from "@/stores";
import { fetchUser } from '@/stores/user';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const token = getToken()
  await store.dispatch(fetchUser(token))
  const { user } = store.getState().user
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider preloadedState={{
          user: {
            user: {
              ...user,
              deneme: "deneme"
            }
          }
        }}>
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
